# Generated by Django 4.2.5 on 2023-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_comtumuser_remove_user_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
