# Generated by Django 4.2.5 on 2023-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_user_token_user_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default=1),
        ),
    ]
