# Generated by Django 4.2.5 on 2023-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comtumuser',
            name='employee_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
