# Generated by Django 4.2.5 on 2023-11-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_registeruser_delete_comtumuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComtumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
