# Generated by Django 4.2.5 on 2023-11-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_comtumuser_delete_registeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComtumUser',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
